.github/workflows/pr-commands.yaml, NEWS.md
Error:
> Invalid workflow file: .github/workflows/pr-commands.yaml#L11
The workflow is not valid. .github/workflows/pr-commands.yaml (Line: 11, Col: 9): Unexpected symbol: ')'. Located at position 203 within expression: github.event.issue.pull_request && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') || github.event.comment.author_association == 'CONTRIBUTOR') && startsWith(github.event.comment.body, '/document') .github/workflows/pr-commands.yaml (Line: 48, Col: 9): Unexpected symbol: ')'. Located at position 203 within expression: github.event.issue.pull_request && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') || github.event.comment.author_association == …
=> Bugfix: Extra paren in CI command

.github/workflows/pr-commands.yaml, NEWS.md
In #22 we fixed /document by expanding the number of scopes that could
call the command. Here we do the same thing for /style.
The other change is from the default github token to a token that I've
provided the repo. This change allows the pushed commits with the
auto-styled or -documented code to re-start CI.
=> Additional small CI tweaks

NEWS.md, R/read_data.R, tests/testthat/_snaps/read_data.md, tests/testthat/test-read_data.R
From @damonbayer:
> Fixes two bugs:
>
>The expected rows in the error message were off by one compared to the expected rows in the error check.
If any rows were missing, all of the reference_dates would be reported as missing because expected_dates and df[["reference_date"]] were of different types.
I add the additional changes to 20d77fc6c95b3a794c3971884652af64e75f662a:
1. Fix the lint error in the creation of `missing_dates`
2. Reformat `missing_dates` to a string so that the missing dates are
pretty-printed. They're printed as an int if they're left as dates.
3. Update the test for this warning to a classed **snapshot** test.
This change should prevent regression of the warning message.
=> Take 2: Fix `read_data()` incomplete return warning message

NEWS.md, R/parameters.R, R/read_data.R
To fix test failures caused by DuckDB v1.1.1 release
=> Explicit date casting in queries

Makefile, NEWS.md, R/fit_model.R, tests/testthat/test-fit_model.R
It was already documented as `iter_sampling` in the docs, but the code
expected `iter_samples`.
`iter_sampling` follows `{cmdstanr}` syntax: https://mc-stan.org/cmdstanr/reference/model-method-sample.html
`iter_samples` is an accidental portmanteau of EpiNow2's desired
`samples` arg and `iter_sampling`.
Also added a few quality-of-life Makefile utilities
Closes #73
=> Update key `iter_samples` to `iter_sampling`

NEWS.md, R/parameters.R, man/read_disease_parameters.Rd, man/read_interval_pmf.Rd, tests/testthat/_snaps/parameters.md, tests/testthat/helper-write_parameter_file.R, tests/testthat/test-parameters.R
Update reader to expect a reference date column. This change was a bit
finicky because we want to ignore the column when reading a GI or delay
and use the column when reading right-truncation.
I excuted this logic with an additional if block, but it tripped the
cyclocomp linter. I thought about it a bit, but still think this is the
cleanest approach (as opposed to breaking out the right-truncation
reader as its own special case or doing a post-read pre-check filter).
So I moved the checking into its own helper and left the dedicated
reader logic in the main function.
I also added some additional CLI info text on what the right-truncation
filter is looking for and what was selected. I think it's helpful, but
open to feedback that it's too much.
Closes #70
=> Read from new parameters schema

NEWS.md, R/fit_model.R, R/parameters.R, tests/testthat/_snaps/fit_model.md, tests/testthat/test-fit_model.R
I attempted to do a shadow local run this week alongside the production run. I only ran one state-disease pair.
I had quite a few issues with reading the parameters. Some of those I've noted in #56 and fixed here. Others I've noted in the parameters repo.
Closes #56
=> cleanup from attempted run

.github/workflows/1_pre-Test-Model-Image-Build.yaml, NEWS.md, README.md
This pull request includes several enhancements and modifications to the GitHub Actions workflow file `.github/workflows/1_pre-Test-Model-Image-Build.yaml`. The changes focus on improving the build process, adding commit message handling, and enhancing the Azure Batch pool creation logic.
Azure Batch pool creation:
* Added a conditional step to check if the Azure Batch Pool already exists before attempting to create it, preventing redundant pool creation.
* ~~Pools can be re-built via commit message by passing the tag `[re-build pool]`.~~
* Pools can be deleted via commit message by passing adding the tag `[delete pool]`. Will only work if a pool with the branch name was created.
* ~~Tags `[re-build pool]` and `[delete pool]` can be combined.~~
> [!IMPORTANT]
Trying to pre-clean the job …
=> Conditionally create the pool if non-existing

R/extract_diagnostics.R, man/Exclusions.Rd, man/extract_diagnostics.Rd
Clarified:
* "These diagnostics are then flagged if they exceed specific thresholds" makes it sound like the returned dataframe flags each _individually_ (which it doesn't, hence suggest change of language)
* "Exceed specific thresholds": sometimes it's if the value is below a threshold hence I suggest reword to "outside acceptable range"
Two possible refactors / improvements of this function could be:
<details>
1. Return a flag for each diagnostic rather than for all of them jointly. Would it ever be useful to know in particular which diagnostic was violated (straight away, I know it could be recovered with some digging)
2. Allowing setting of the thresholds. As a user I imagine this might be useful, like if certain conditions mean that diagnostics are over or under flagging. I can see …
=> Language clarification in `extract_diagnostics`

NEWS.md, R/pipeline.R, R/utils.R, R/write_output.R, man/pipeline.Rd, tests/testthat/helper-expect_pipeline_files_written.R, tests/testthat/test-pipeline.R
* Change formatting of metadata values to be atomic. Test that this is the case. May have to change this at some point, if we ever add non-atomic fields on purpose.
* Add `blob_storage_container` as a field to the metadata.
* Use empty string for paths when non-existant.
=> Make metadata easier to use.

Makefile
`azure/job.py` expects `config_container` to be the second argument.
https://github.com/CDCgov/cfa-epinow2-pipeline/blob/2a9798c65ef4e36a3a660987371184d0086716af/azure/job.py#L17
The makefile didn't have it yet.
=> fix call to job.py from make

NEWS.md, R/parameters.R, tests/testthat/test-parameters.R
Previously a same-day as-of date would have erorred as unable to match
a day, rather than correctly reading for the given start date
=> Read same-day parameters

NEWS.md, R/fit_model.R
=> Don't emit DEBUG-level logs from EpiNow2

.github/workflows/containers-and-az-pool.yaml
As a potential fix to the cache causing the runner to run out of memory.
Closes #93
=> Turn off Docker cache on runner

.github/workflows/delete-pool-on-pr-close.yaml, NEWS.md
This workflow _should_ clean up the associated Batch pool when closing
the PR.
It doesn't clean up the associated tagged image in ACR (that's harder)
or jobs that were run on the pool. It would be nice to auto-delete any
linked jobs, but it seems tricker than I'd want? I'll plan to revisit
that when moving this into a dedicated action outside this repo.
Closes #62
=> Workflow to close PR pool on close

.github/workflows/delete-pool-on-pr-close.yaml
The first run threw:
> Invalid workflow file: .github/workflows/delete-pool-on-pr-close.yaml#L11
The workflow is not valid. .github/workflows/delete-pool-on-pr-close.yaml (Line: 11, Col: 5): Unexpected value 'runs_on' .github/workflows/delete-pool-on-pr-close.yaml (Line: 11, Col: 5): Required property is missing: runs-on
See here:
https://github.com/CDCgov/cfa-epinow2-pipeline/actions/runs/12773389898
=> Remove pool delete workflow typo

.github/workflows/delete-pool-on-pr-close.yaml
Latest error is
> Starting script execution via docker image mcr.microsoft.com/azure-cli:latest
WARNING: Unable to load extension 'azure-batch-cli-extensions: No module named 'distutils''. Use --debug for more information.
WARNING: Unable to prompt for confirmation as no tty available. Use --yes.
ERROR: Operation cancelled.
Error: Error: az cli script failed.
cleaning up container...
=> Don't prompt for input (add `--yes`)

.github/workflows/containers-and-az-pool.yaml, Makefile, NEWS.md, azure/job.py
This PR drops the `test-` prefix so that everything is strictly named based off of the branch. It also updates the job & task deployment to use the new naming scheme and make the process more transparent.
The updates to the `azure/job.py` make it easier to kick off a job via GHA but it doesn't actually implement this step. Instead it's left as an update in the Makefile. I've made a new issue, #164 to track the GHA deployment but don't assign it a priority because I'm not sure it's imminently needed -- it'll be worth re-assessing if it would be helpful as we start running this pipeline more.
Closes #87 
I'm also going to say this closes #48. The job setup is now handled as needed by this script.
I ran this PR over a couple of vintages in Batch. Everything ran successfully but note that …
=> Drop test prefix

.github/scripts/cleanup-on-pr-close.sh, .github/workflows/cleanup-on-pr-close.yaml, NEWS.md
And move complete logic into a new shell script to support local runs.
This change cleans up the logic quite a bit.
Also drop the stuff to support running on main because of the PR dependence
that goes with the cleanup action.
=> Delete jobs with pools

Makefile, NEWS.md, azure/job.py
Closes #142 --
Allows the user to provide a job_id to the config generation in `Makefile`. Filters tasks in `azure/job.py` by the job_id instead of time created.
I still need to test this in Batch -- my understanding is this PR will spin up a new pool. Do I just need to run `make run-batch` to test this? @zsusswein @natemcintosh
=> Updating config workflow

Makefile, azure/job.py
Some follow-up to #151.
Fixes the timing to wait for the configs to make it to Blob and
cleans up the Batch job name.
=> Clean up Batch job launch

Makefile, NEWS.md, azure/job.py
Closes #176 --
Creates a timestamp based `job_id` that gets passed to the config generator, only those job_ids are pulled in `job.py`. We also fix the batch job name to the pool name, so any tasks get appended to those (instead of creating a new one each run).
Tested in Batch by running
`make run-batch` in pool `cfa-epinow2-am-unique-job-id`
=> Unique job_id and fixed batch_job_id

NEWS.md, R/pipeline.R
The metadata previously saved the path to an exclusions file (if provided). However it did not provide the name of the blob storage container (if provided). This adds that so that we can more easily see where the given exclusions file lives.
This pull request includes updates to the `CFAEpiNow2Pipeline` to add support for blob storage containers and to correct an oversight in the model diagnostics output. The most important changes include updates to the `NEWS.md` file and modifications to the `execute_model_logic` function in `R/pipeline.R`.
* Added a note about the new feature to add the blob storage container if provided.
* Modified the `execute_model_logic` function to include `exclusions_blob_container` and renamed `exclusions` to `exclusions_path` for clarity.
=> Add the blob container name for exclusions to metadata

Makefile, NEWS.md, SOP.md
I adjusted some of the syntax in the Makefile here so we have more customizable chunks of make commands in the Makefile. i.e. 'make run-prod' will now be the command to run the weekly pipeline in production while 'make run-batch' should be run after a custom config call. 
Testing of new make commands 'make run-prod' and the 3 steps under Task Exclusions shown to work without issue
=> Doc add task exclusions mpw

NEWS.md, SOP.md
This adds instructions on how to rerun, as well as some context around data outlier reruns.
The rendered mermaid diagram can be [found here](https://github.com/CDCgov/cfa-epinow2-pipeline/blob/89ff6a9db14069ed60b629f8c4ddf9f9858acc10/SOP.md)
This pull request includes updates to the `SOP.md` file to improve clarity and provide more detailed instructions for handling data exclusions and generating configurations. The most important changes include adding a new section on data exclusions, updating instructions for generating configurations, and correcting minor formatting issues.
Enhancements to data exclusions process:
* Added a detailed explanation and flowchart for handling data exclusions during anomaly review meetings, including the steps for documenting decisions, verifying data, and …
=> Add data outliers rerun instructions

Makefile, NEWS.md
Add sleep_time as parameter to Makefile to compensate for slow spin up times on cfa-config-generator container app
=> adding sleep time as parameter to makefile

Dockerfile-batch, Makefile, NEWS.md, SOP.md, azure/job.py
This swaps us from using the separate `Dockerfile-batch` (just for submitting to Batch) to a single [inline-metadata script](https://packaging.python.org/en/latest/specifications/inline-script-metadata/#inline-script-metadata) with all of the necessary packages described in the metadata. We run it with `uv`, which (thankfully) takes the exact same `--env-file .env` argument as Docker for putting stuff into the environment it runs in.
I have tested this in Batch, and it runs as expected. 
Oh, and apparently `job.py` was not formatted, so this includes those formatting changes as well.
This pull request includes significant changes to the batch job system, primarily focusing on the removal of Dockerfile usage, updates to the Makefile for running jobs, and refactoring the `azure/job.py` …
=> Swap job.py from running in Docker to being an inline metadata script

.github/workflows/pkgdown.yaml, .github/workflows/r-cmd-check.yaml, .github/workflows/test-coverage.yaml, NEWS.md
Pinning to r-version that is stable instead of latest (r-vers: 4.5 is causing issues with r-setup / build).
=> Pin r version to 4.4.3 for CICD

.github/scripts/delete-container-tag.sh, .github/workflows/delete-container-tag.yaml, NEWS.md
I updated the delete-container-tag.yaml job to delete from GHCR as well as ACR when a pull request is closed. I added an input to the workflow_dispatch so we can use the same workflow to manually clean up past images.
There are two separate jobs that are set up with `continue-on-error` so workflow can still be used if an image tag has already been removed from one of the container registries without failing the whole pipeline and cancelling the other job.
While I was in there, I switched from using the service principal secret to OIDC login (also done in #177) so we don't have to worry about rotating credentials in 2026. I also removed the dependency image tag deletion since we switched to a unified Dockerfile a while back.
I used a third-party action to delete the image tag from GHCR …
=> deleting tag from ghcr + OIDC login

.github/scripts/create_pool.py, NEWS.md
This is also a useful time to check that the new [pool creation CI](https://github.com/CDCgov/cfa-epinow2-pipeline/pull/177) works as expected, and creates a pool for this branch.
For future reference, I was able to find the exact versions that `uv` resolved by running
```sh
uv lock --script .github/scripts/create_pool.py
```
Which produced `.github/scripts/create_pool.py.lock`. I then searched through the lock file to find the exact versions for each top-level dependency in the script itself.
=> Add locked versions for future stability

.github/workflows/cleanup-on-pr-close.yaml, .github/workflows/delete-container-tag.yaml, NEWS.md
Turns out you can't clone a repo at a specific commit:
https://github.com/CDCgov/cfa-epinow2-pipeline/actions/runs/15071381724/job/42368337662
This PR just clones the default branch and checks out the specific commit after.
=> fixing tag and pool deletion workflows

NEWS.md, utils/Rt_review_exclusions.R
Convert "Drop Date(s)" Column Values in Rt_Review Excel to string/character. Occasionally reads in as double. Editing template doesn't seem to address this. Simple fix, just adding in line to convert column value to character.
=> Convert "Drop Date(s)

NEWS.md, utils/Rt_review_exclusions.R
These code changes should remove nulls associated with reference_dates whenever we produce the outlier csvs.
=> removes nulls that are produced in outliers.csv file 

NEWS.md, utils/Rt_review_exclusions.R
This update prevents saving the point exclusions file if the values under the column names are empty. This continues to save the point exclusions file if values are present.
We have a comparison of code output from 20240514 (where no values are present) to 20240611 (where values are present)
=> save point exclusions file only if data values are present

Makefile, NEWS.md
We've recently had issues with developers running 'make document' locally without entering the docker image (this means it is being run from their global R environment in their VAP). This has caused some issues with documentation.
This will make these commands unified for all users running in their VAP.
This make command will make it more explicit that CI processes / checks should be run from the docker image if run locally.
To test, please run. 
1. make document
=> update make file with CI practices

.github/workflows/run-prod.yaml, NEWS.md
This change moves the time of the production run up to 11 AM UTC.
This adjustment in timing should reduce the number of hours needed
to wait for runs to complete, requiring less time to maintain
production activities.
This timing is the same as for the HGAM runs, which have been
successful for multiple weeks now.
=> Move production run earlier
