CDCgov/cfa-epinow2-pipeline

- .github/workflows/pr-commands.yaml
- DESCRIPTION
- NEWS.md
- R/add.R
Some more testing for the non-functional /document workflow.
This version worked fine in a fork into my personal account, so either this yaml works or I need to dive into the settings some more.
> zs testing workflows

- .github/workflows/pr-commands.yaml
- NEWS.md
per https://github.com/orgs/community/discussions/26220
> Don't persist credentials so PAT is used on push

- .pre-commit-config.yaml
- NEWS.md
From the template repo that are for non-R languages.
Closes #57
> Drop unused hooks

- NEWS.md
- R/write_output.R
Additional NSE problems.
Closes #75
> Fix NOTE from unassigned variable

- NEWS.md
- README.md
This pull request includes an update to the `README.md` file to add a visual representation of the CI/CD process using a Mermaid diagram.
Documentation update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R117-R150): Added a Mermaid flowchart to visually represent the CI/CD process, detailing the steps from start to creating and managing pools.
> Adding mermaid diagram and note on naming branches

- NEWS.md
- R/read_data.R
- man/read_data.Rd
This has also been a useful way for me to get up to speed on how docker is working for this repo. I think I should be able to pull the `cfa-epinow2-pipeline-dependencies` image to speed up build and running the regular `Dockerfile`, but I haven't figured out the right invocation yet. I'll see if I can get `make` to help us `test`, `document`, `check` inside the container maybe?
> Mention us is option

- NEWS.md
- azure/requirements.txt
Should fix pool build, which is currently failing
> Include missing deps in venv

- NEWS.md
- R/azure.R
- man/fetch_blob_container.Rd
This PR closes #110. I think it's clearest not to describe the function as "impure" and to be more direct about it.
> Issue #110: Improve documentation of `fetch_blob_container()`

- Makefile
- NEWS.md
It wasn't properly setting `TAG` to `latest` when on main. Now it does.
> fixed main TAG issue

- Dockerfile-dependencies
- NEWS.md
To prevent R CMD check failing in the second-step image
Closes #146
> Install `suggests` into first-step image

- .github/workflows/delete-pool-on-pr-close.yaml
> Properly name runner

- .github/workflows/delete-pool-on-pr-close.yaml
> Need $ for variables

- .github/workflows/delete-pool-on-pr-close.yaml
> Use a secret for the Batch account

- .github/workflows/cleanup-on-pr-close.yaml
> Fix typo causing failing workflow

- NEWS.md
> Clean up for release

- .github/workflows/delete-container-tag.yaml
- NEWS.md
The delete container tag workflow file needed a backslash.
> Small bug in delete-container-tag.yaml

- .github/workflows/containers-and-az-pool.yaml
- NEWS.md
- azure/pool.py
This pull request includes several updates to the Azure pool configuration and documentation. The main changes involve adding a new environment variable for the subnet ID, updating the VM configuration, and cleaning up the code.
Azure pool configuration updates:
* [`.github/workflows/containers-and-az-pool.yaml`](diffhunk://#diff-ff3a54eba2ed032aff1e25077eb32d48be0c54166b17d593e2f7728d99b69394R85): Added `BATCH_SUBNET_ID` to the environment variables and updated the `sed` command to replace the `{{ BATCH_SUBNET_ID }}` placeholder in the `pool-config-<sha>.toml` file. [[1]](diffhunk://#diff-ff3a54eba2ed032aff1e25077eb32d48be0c54166b17d593e2f7728d99b69394R85) [[2]](diffhunk://#diff-ff3a54eba2ed032aff1e25077eb32d48be0c54166b17d593e2f7728d99b69394R105)
Documentation updates:
* …
> Dev update subnet mpw

- .github/workflows/start-app-job.yaml
- NEWS.md
Provides a manually triggered GitHub Actions workflow that executes an Azure Container App Job running this pipeline. Requires the config file be specified as user input.
> Added GitHub Actions workflow to start Azure Container App Job

- NEWS.md
- SOP.md
This has the updates to the documentation about where we store the data outliers files.
> Update outliers path documentation

- Makefile
- NEWS.md
- azure/job.py
Adding logic to query for the configs in blob every X (likely 15) seconds to accomodate on-demand and slower spin up azure container apps runner setup
> Dev config gen sensing

- .github/scripts/create_pool.py
- .github/workflows/containers-and-az-pool.yaml
This PR replaces the self-hosted runner with the runner-action to comply with CDC Github's request to disable self-hosted runners for CDCgov repos. I also used identity authentication for the registry instead of a username and password. Seems to be working!
> moving from self hosted runner to runner-action

- NEWS.md
- SOP.md
I am reading and working through the SOP for use in my work on the parameter estimates repository `cfa-parameter-estimates`.
To aid my understanding and perhaps contribute I thought it was worth proposing some edits. (I don't have strong opinions here, so up to reviewers to take or leave suggestions.)
> Possible edits to SOP document

- Makefile
- NEWS.md
- azure/generate_configs.py
- azure/generate_rerun_configs.py
- azure/job.py
This PR is all about cutting out the middleman: generating the configs on GitHub Actions. Instead of having the workflow run, and waiting for it to finish before submitting the jobs, this adds scripts which call the same config generation functions as in the workflow, but locally.
And since we no longer have to wait for the GitHub Action to run (the config files will always have been uploaded by the end of `make config` and `make rerun-config`), we can also remove the loop in `job.py` that waits for the config files to be uploaded.
If this new method produced config files that didn't exactly match those from before, we'd be in trouble. To make sure that wasn't the case, I ran tests to produce and programmatically compare the config files for:
1. all states, all diseases
2. all states, …
> Generate configs by calling config generator library directly

- NEWS.md
- R/parameters.R
- R/read_data.R
- man/Config.Rd
- man/extract_diagnostics.Rd
- man/read_data.Rd
- man/read_disease_parameters.Rd
- man/read_interval_pmf.Rd
- man/sample_processing_functions.Rd
Issue link https://github.com/CDCgov/cfa-epinow2-pipeline/issues/264
> Add RSV where COVID and Influenza specified

- DESCRIPTION
- NEWS.md
- README.md
This is a draft PR to close #250.
Let me know current code owners (tagged to review) plus Micah if you'd like something different.
> Issue #250: Change project owner

- DESCRIPTION
- NEWS.md
Closes #280. See comment from Zach here that I missed: https://github.com/CDCgov/cfa-epinow2-pipeline/pull/274#pullrequestreview-2846737433
> Issue #280: Change from contributors to authors

- Makefile
- NEWS.md
Will close #273. Where it is now:
For reviewers:
* What do you think of the documentation? Anything wrong or could be better?
* Tried to simplify `run-batch`, `run-prod`, and `rerun-prod` (need to test this)
* Any targets we don't need? Any which could be simplified?
> Issue #273: Document Makefile

- NEWS.md
- azure/generate_configs.py
Good morning, this code change adds the facility active proportion field to the cfa-epinow2-pipeline repo after its addition to the cfa-config-generator repo last week.
> adds facility active proportion field

- NEWS.md
- azure/generate_rerun_configs.py
In addition to the facility_active_proportion's inclusion in the config runs, this code also applies it to the re-runs.
> adds facility active proportion to config re-runs

- .pre-commit-config.yaml
- NEWS.md
Adding a pre commit hook to ensure that a specific file is not re committed to repo.
To test the following code.
1. touch tests/testthat/data/2025-04-02_test.parquet
2. git add -f tests/testthat/data/2025-04-02_test.parquet
3. uv run --with 'pre-commit' pre-commit run --all-files
> Dev precommit update testfile

- NEWS.md
- utils/Rt_review_exclusions.R
This pull request adds RSV as an argument for pulling data point and state exclusions from our weekly excel file used to record those decisions.
> Pulls RSV exclusions from exclusions file
